### ISSUE TITLE
Feedback - Week 8 Project

### ISSUE THREAD

**Issue by ntuvera** [JcWilliams291/O-Town#13]
Hey @msallam227, @vporta, @JasonMartocci, @JcWilliams291, I cloned your repo and took a look at Health-Box...

UI/UX:

Local View looks like it's hard-coded longitude & latitude.  You could try something like this (https://developers.google.com/web/fundamentals/native-hardware/user-location/obtain-location?hl=en), which should allow you to grab your current position (assuming the user allows their browser to retrieve location) and then if they choose not to, hide the map div.

Search Bar responsiveness doesn't always play well on window resizing.  I think it's thrown into a jumbotron, but no corresponding `row`/`col-md-#` to keep it Bootstrapped. 

edamam modals, self created divs or prepackaged??

Not really sure, what Flickr Fitness' purpose is.  If I search for anything, it seems to return the same set of pictures.  Was it worth keeping?

Firebase chat application is nice, but feels incomplete.  Lacks validations for empty inputs.

Code Style/Design:

The majority of your code looks, cleanly indented and commented very nicely.  There were a few extra white spaces which don't affect the codes functionality or readability, but they are still there.  You may want to look into something like ESLint, which can parse your javascript and fix errors in both syntax _and_ styling.  Overall, it's been very easy to read although it does feel a bit all over the place in some files like `app.js`, where it could've been separate functionalities in different files.

Code Technical:

My assumption is that you guys ran into issues with Git Merging, since I look at the contributors to the repo and it's 96% commits only from @JasonMartocci.  Fair enough, we're going to have a lesson day planned around Git workflows and merges.

Why are there image assets in your `assets/css` & `assets/javascript` folders?  It may have been an oversight that needed to be cleaned up, but it shouldn't be there in the first place.

Also you've got publicly exposed API keys now that we've pushed them all to Github, luckily these keys can be thrown away later.  Moving forward with Node and express, we'll show you how you can hide important information like this using environment variables for deployment as well as require exports for local.

Overall:
There's a lot going on here, not sure what the focus is.  

I based most of my feedback on a local git clone of the repository.  If you moved the code to another repo OR pushed up something different to Heroku let me know.  I realize later after opening the deployed version some things work differently than on my local copy.  Although they should be the same, so I'm a little confused on your workflow.

You've demonstrated technical ability in spades, you picked APIs and got them working.  From a technical aspect, it's great.  From UI/UX perspective, I don't think the project/app was focused enough.  It feels like just a bunch of feeds that I don't think tie into the name Health-box.

**Comment by JasonMartocci** [comment]
Thanks for the feedback. I will look into making the suggested updates along with updating the latest folder.
